### ISSUE TITLE
topologySpreadConstraints are needed

### ISSUE THREAD

**Issue by dl-kahara** [dl-kahara/run-rabbitmq#3]
Out-of-the-box, `RabbitmqCluster` runs with the following:

```yaml
topologySpreadConstraints:
  - labelSelector:
       matchLabels:
         app.kubernetes.io/name: rabbitmq
     maxSkew: 1
     topologyKey: topology.kubernetes.io/zone
     whenUnsatisfiable: ScheduleAnyway
```

Which may not work in an on-prem, single-site setting for example. Consider spreading by hostname, as described in [the docs](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#more-practical-use-cases):

```yaml
topologyKey: kubernetes.io/hostname
```

How this should be communicated to the Operator is tbd.
